# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
# from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import *
from functools import partial
from PyQt5.QtGui import QKeyEvent
from PyQt5.QtCore import Qt, QCoreApplication
from Screen.MainWindow import MainWindow
from PyQt5.QtGui import QCloseEvent

from pathlib import Path
sys.path.append(str(Path(__file__).parents[1]))
from Database.DB import DBManager
from Helper import *
from Settings import Setup as sp
        

class UI_Setup_Field(QWidget, DBManager):
    def __init__(self, mainwindow):
        super().__init__()
        self.cnt = 0
        self.mainwin = mainwindow
        self.start = True
        self.sp = sp.Settings()

    @AutomationFunctionDecorator
    def setupUI_Field(self):
        # 언어별 경로 설정 메인 창
        if self.start:
            self.resize(600, 400)
            self.setWindowTitle("엑셀에 추가할 필드 설정")

            # 전체 화면 배치
            self.verticalLayout = QVBoxLayout(self)

            # DB에서 언어 설정 불러옴
            result_val, result_val2 = self.sp.read_ini_test(table = "Field")

            dataList = [] # 인자 1개만 필요할시 List 출력
            print(len(result_val))
            for i in result_val:
                dataList.append(i)

            if len(dataList) > 0:
                for data in dataList:
                    self.set_data()
                    print(f'cnt : {self.cnt}')
                    print(f'data : {data}')
                    globals()[f'lineEdit{self.cnt-1}'].setText(data)

                if len(dataList) < 6:
                    for _ in range(6-len(dataList)):
                        self.set_data()

            else:
                for _ in range(6):
                    self.set_data()

            # [확인], [취소] 버튼
            self.ok_horizontalLayout = QHBoxLayout()
            self.ok_horizontalLayout.setAlignment(Qt.AlignRight)
            
            self.ok_Button = QPushButton("확인", self)
            self.ok_horizontalLayout.addWidget(self.ok_Button)
            self.cancel_Button = QPushButton("취소", self)
            self.ok_horizontalLayout.addWidget(self.cancel_Button)
            self.verticalLayout.addLayout(self.ok_horizontalLayout)

            # 버튼 이벤트 함수
            self.sl_set_slot()

        self.start = False

    @AutomationFunctionDecorator
    def set_data(self):
        globals()[f'horizontalLayout{self.cnt}'] = QHBoxLayout()

        globals()[f'label{self.cnt}'] = QLabel()
        globals()[f'label{self.cnt}'].setText(f"{self.cnt+1}")
        globals()[f'horizontalLayout{self.cnt}'].addWidget(globals()[f'label{self.cnt}'])

        globals()[f'lineEdit{self.cnt}'] = QLineEdit()
        globals()[f'horizontalLayout{self.cnt}'].addWidget(globals()[f'lineEdit{self.cnt}'])

        # 0725
        for val in range(self.cnt + 1):

            if globals()[f'lineEdit{val}'].text() == "":
                globals()[f'lineEdit{val}'].setFocus()
                break

        self.verticalLayout.addLayout(globals()[f'horizontalLayout{self.cnt}'])

        self.cnt += 1

    @AutomationFunctionDecorator
    def sl_set_slot(self):
        self.ok_Button.clicked.connect(partial(self.ok_Button_clicked))
        self.cancel_Button.clicked.connect(self.close)

    @AutomationFunctionDecorator
    def ok_Button_clicked(self, litter):
        checkOverlap = []

        # 중복 체크
        for i in range(1, self.cnt):
            if globals()[f'lineEdit{i}'].text() != "":
                if globals()[f'lineEdit{i}'].text() not in checkOverlap:
                    checkOverlap.append(globals()[f'lineEdit{i}'].text())
                else:
                    QMessageBox.about(self, '주의', '중복 라인이 있습니다.')
                    return

        # DB에 저장
        # 0728
        self.c.execute(f"DELETE FROM Setup_Field")
        self.sp.create_table(table="Field")
        for i in range(self.cnt):
            if globals()[f'lineEdit{i}'].text() != "":
                try:
                    self.test = self.sp.with_ini_test(table = "Field", 
                        count=i, 
                        val=globals()[f'lineEdit{i}'].text(),
                        val2=None)
                    self.dbConn.execute(f"INSERT INTO Setup_Field VALUES (?)", 
                            ((globals()[f'lineEdit{i}'].text(),)))
                    
                except RuntimeError:
                    continue

        self.sp.save_ini(self.test) # 여기수정
        self.dbConn.commit()

        for i in range(self.mainwin.field_gridLayout.count()):
            self.mainwin.field_gridLayout.itemAt(i).widget().deleteLater()
        self.mainwin.set_field()

        self.close()
        
    @AutomationFunctionDecorator
    def closeEvent(self, event) -> None:
        self.c.execute('SELECT * FROM Setup_Field')
        dataList = self.c.fetchall()
        temp_cnt = 1

        dbList = [data[0] for data in dataList]
        lineList = [globals()[f'lineEdit{i}'].text() for i in range(self.cnt) if globals()[f'lineEdit{i}'].text() != ""]

        if dbList != lineList:
            reply = QMessageBox.question(self, '알림', '변경사항이 있습니다.\n취소하시겠습니까?',
                                    QMessageBox.Yes | QMessageBox.No, QMessageBox.No)

            if reply == QMessageBox.Yes:
                for i in range(self.cnt):
                    globals()[f'lineEdit{i}'].setText("")

                if len(dataList) > 0:
                    for data in dataList:
                        globals()[f'lineEdit{temp_cnt-1}'].setText(data[0])
                        temp_cnt += 1
                event.accept()
            else:
                event.ignore()
                
        self.mainwin.setDisabled(False)

    # 0725
    @AutomationFunctionDecorator
    def keyPressEvent(self, a0: QKeyEvent) -> None:
        
        KEY_ENTER = 16777220
        KEY_SUB_ENTER = 16777221

        print (f"a0.key() : {a0.key()}")
        if a0.key() == KEY_ENTER or a0.key() == KEY_SUB_ENTER:
            self.ok_Button_clicked(None)
        elif a0.key == KEY_ENTER:
            self.close()

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    ui = UI_Setup_Field()
    ui.setupUi_Field()
    ui.show()
    sys.exit(app.exec_())
