# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1472, 876)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 70, 821))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.img_VBoxLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.img_VBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.img_VBoxLayout.setObjectName("img_VBoxLayout")
        self.border()
        self.img_VBoxLayout.addWidget(self.lbl_border)
        self.img_Label = QtWidgets.QLabel(self.centralwidget)
        self.img_Label.setGeometry(QtCore.QRect(90, 10, 1350, 621))
        self.img_Label.setText("")
        self.img_Label.setObjectName("img_Label")
        self.img_Label.setStyleSheet("color: gray;"
                             "border-style: solid;"
                             "border-width: 1px;"
                             "border-color: #747474;"
                             "border-radius: 1px")
        self.desc_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.desc_LineEdit.setGeometry(QtCore.QRect(300, 650, 675, 20))
        self.desc_LineEdit.setObjectName("desc_LineEdit")
        self.desc_LineEdit.setText("")
        self.desc_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 690, 1141, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.testList_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.testList_Layout.setContentsMargins(0, 0, 0, 0)
        self.testList_Layout.setObjectName("testList_Layout")
        self.border()
        self.testList_Layout.addWidget(self.lbl_border)
        self.save_Button = QtWidgets.QPushButton(self.centralwidget)
        self.save_Button.setGeometry(QtCore.QRect(1280, 650, 131, 31))
        self.save_Button.setObjectName("save_Button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1300, 690, 161, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.testAll_VBoxLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.testAll_VBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.testAll_VBoxLayout.setObjectName("testAll_VBoxLayout")
        self.allPass_RadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.allPass_RadioButton.setObjectName("allPass_RadioButton")
        self.testAll_VBoxLayout.addWidget(self.allPass_RadioButton)
        self.allNA_RadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.allNA_RadioButton.setObjectName("allNA_RadioButton")
        self.testAll_VBoxLayout.addWidget(self.allNA_RadioButton)
        self.allNT_RadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.allNT_RadioButton.setObjectName("allNT_RadioButton")
        self.testAll_VBoxLayout.addWidget(self.allNT_RadioButton)
        self.allFail_RadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.allFail_RadioButton.setObjectName("allFail_RadioButton")
        self.testAll_VBoxLayout.addWidget(self.allFail_RadioButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1472, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.setup = QtWidgets.QMenu(self.menubar)
        self.setup.setObjectName("setup")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen.setStatusTip("Open Image")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen.setStatusTip("Close Application")
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionOpen.setStatusTip("Setup Language")
        self.actionTest_List = QtWidgets.QAction(MainWindow)
        self.actionTest_List.setObjectName("actionTest_List")
        self.actionOpen.setStatusTip("Setup Test List")
        self.actionExcel_Setting = QtWidgets.QAction(MainWindow)
        self.actionExcel_Setting.setObjectName("actionExcel_Setting")
        self.actionOpen.setStatusTip("Setup Excel Setting")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionClose)
        self.setup.addAction(self.actionLanguage)
        self.setup.addAction(self.actionTest_List)
        self.setup.addAction(self.actionExcel_Setting)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.setup.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def border(self):
        self.lbl_border = QtWidgets.QLabel('')
        self.lbl_border.setStyleSheet("color: gray;"
                             "border-style: solid;"
                             "border-width: 1px;"
                             "border-color: #747474;"
                             "border-radius: 1px")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "다국어 자동화"))
        self.save_Button.setText(_translate("MainWindow", "저장"))
        self.allPass_RadioButton.setText(_translate("MainWindow", "ALL PASS"))
        self.allNA_RadioButton.setText(_translate("MainWindow", "ALL FAIL"))
        self.allNT_RadioButton.setText(_translate("MainWindow", "ALL N/T"))
        self.allFail_RadioButton.setText(_translate("MainWindow", "ALL N/A"))
        self.menu.setTitle(_translate("MainWindow", "Menu"))
        self.setup.setTitle(_translate("MainWindow", "Setup"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionLanguage.setText(_translate("MainWindow", "Language"))
        self.actionTest_List.setText(_translate("MainWindow", "Test List"))
        self.actionExcel_Setting.setText(_translate("MainWindow", "Excel Setting"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
