# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QCoreApplication


class UI_Setup_Language(QWidget):
    def __init__(self):
        super().__init__()

    def setupUi_Language(self, Form):
        Form.setObjectName("Form")
        Form.resize(744, 412)
        self.addLang_Button = QtWidgets.QPushButton(Form)
        self.addLang_Button.setGeometry(QtCore.QRect(307, 10, 130, 31))
        self.addLang_Button.setObjectName("addLang_Button")

        self.langlist_verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.langlist_verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 701, 311))
        self.langlist_verticalLayoutWidget.setObjectName("langlist_verticalLayoutWidget")
        self.langList_VBoxLayout = QtWidgets.QVBoxLayout(self.langlist_verticalLayoutWidget)
        self.langList_VBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.langList_VBoxLayout.setObjectName("langList_VBoxLayout")
        self.langList_scrollArea = QtWidgets.QScrollArea(self.langlist_verticalLayoutWidget)
        self.langList_scrollArea.setWidgetResizable(True)
        self.langList_scrollArea.setObjectName("langList_scrollArea")
        self.langList_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.langList_scrollAreaWidgetContents.setGeometry(QtCore.QRect(20, 50, 701, 311))
        self.langList_scrollAreaWidgetContents.setObjectName("langList_scrollAreaWidgetContents")
        self.langList_scrollArea.setWidget(self.langList_scrollAreaWidgetContents)
        self.langList_VBoxLayout.addWidget(self.langList_scrollArea)

        self.sl_ok_horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.sl_ok_horizontalLayoutWidget.setGeometry(QtCore.QRect(560, 370, 161, 31))
        self.sl_ok_horizontalLayoutWidget.setObjectName("sl_ok_horizontalLayoutWidget")
        self.sl_ok_horizontalLayout = QtWidgets.QHBoxLayout(self.sl_ok_horizontalLayoutWidget)
        self.sl_ok_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.sl_ok_horizontalLayout.setObjectName("sl_ok_horizontalLayout")
        self.ok_Button = QtWidgets.QPushButton(self.sl_ok_horizontalLayoutWidget)
        self.ok_Button.setObjectName("ok_Button")
        self.sl_ok_horizontalLayout.addWidget(self.ok_Button)
        self.cancel_Button = QtWidgets.QPushButton(self.sl_ok_horizontalLayoutWidget)
        self.cancel_Button.setObjectName("cancel_Button")
        self.sl_ok_horizontalLayout.addWidget(self.cancel_Button)

        self.retranslateUi_language(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.sl_set_slot()

    def retranslateUi_language(self, Form):
        self.translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(self.translate("Form", "Form"))
        self.addLang_Button.setText(self.translate("Form", "언어 추가"))
        self.ok_Button.setText(self.translate("Form", "확인"))
        self.cancel_Button.setText(self.translate("Form", "취소"))

    def sl_set_slot(self):
        self.addLang_Button.clicked.connect(self.addLang_Button_clicked)

    def addLang_Button_clicked(self):
        self.lang_LineEdit = QtWidgets.QLineEdit(self.langlist_verticalLayoutWidget)
        self.lang_LineEdit.setObjectName("lang_LineEdit")
        self.lang_LineEdit.setContentsMargins(10, 10, 10, 10)
        self.langList_scrollArea.setWidget(self.lang_LineEdit)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UI_Setup_Language()
    ui.setupUi_Language(Form)
    Form.show()
    sys.exit(app.exec_())
