# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_Setup_Language(object):
    def setupUi_Language(self, Form):
        Form.setObjectName("Form")
        Form.resize(744, 412)
        self.addLang_Button = QtWidgets.QPushButton(Form)
        self.addLang_Button.setGeometry(QtCore.QRect(307, 10, 130, 31))
        self.addLang_Button.setObjectName("addLang_Button")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 701, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.langList_VBoxLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.langList_VBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.langList_VBoxLayout.setObjectName("langList_VBoxLayout")
        self.border()
        self.langList_VBoxLayout.addWidget(self.lbl_border)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(560, 370, 161, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_Button.setObjectName("ok_Button")
        self.horizontalLayout.addWidget(self.ok_Button)
        self.cancel_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_Button.setObjectName("cancel_Button")
        self.horizontalLayout.addWidget(self.cancel_Button)

        self.retranslateUi_language(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        Form.show()

    def retranslateUi_language(self, Form):
        self.translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(self.translate("Form", "Form"))
        self.addLang_Button.setText(self.translate("Form", "언어 추가"))
        self.ok_Button.setText(self.translate("Form", "확인"))
        self.cancel_Button.setText(self.translate("Form", "취소"))

    def border(self):
        self.lbl_border = QtWidgets.QLabel('')
        self.lbl_border.setStyleSheet("color: gray;"
                             "border-style: solid;"
                             "border-width: 1px;"
                             "border-color: #747474;"
                             "border-radius: 1px")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UI_Setup_Language()
    ui.setupUi_Language(Form)
    sys.exit(app.exec_())
