# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QCoreApplication, Qt


class UI_Setup_Language(QWidget):
    def __init__(self):
        super().__init__()

    def setupUi_Language(self):
        # 언어별 경로 설정 메인 창
        self.resize(744, 412)
        self.setWindowTitle("언어별 경로 설정")

        # 전체 화면 배치
        self.verticalLayout = QVBoxLayout(self)

        # [언어 추가] 버튼
        self.sl_addLang_horizontalLayout = QHBoxLayout()
        self.sl_addLang_horizontalLayout.setAlignment(Qt.AlignCenter)
        self.addLang_Button = QPushButton("언어 추가", self)
        self.addLang_Button.setMaximumWidth(130)
        self.sl_addLang_horizontalLayout.addWidget(self.addLang_Button)
        self.verticalLayout.addLayout(self.sl_addLang_horizontalLayout)

        # 언어 설정 리스트 영역
        self.langList_scrollArea = QScrollArea(self)
        self.langList_scrollArea.setWidgetResizable(True)
        self.langList_scrollAreaWidgetContents = QWidget()
        self.langList_scrollAreaWidgetContents.setGeometry(QtCore.QRect(20, 50, 701, 311))
        self.langListScroll_verticalLayout = QVBoxLayout(self.langList_scrollAreaWidgetContents)

        self.langList_verticalLayout = QVBoxLayout()
        self.langList_verticalLayout.setAlignment(Qt.AlignTop)

        self.langList_scrollArea.setWidget(self.langList_scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.langList_scrollArea)

        
        # [확인], [취소] 버튼
        self.sl_ok_horizontalLayout = QHBoxLayout()
        self.sl_ok_horizontalLayout.setAlignment(Qt.AlignRight)
        
        self.ok_Button = QPushButton("확인", self)
        self.sl_ok_horizontalLayout.addWidget(self.ok_Button)
        self.cancel_Button = QPushButton("취소", self)
        self.sl_ok_horizontalLayout.addWidget(self.cancel_Button)
        self.verticalLayout.addLayout(self.sl_ok_horizontalLayout)

        # 버튼 이벤트 함수
        self.sl_set_slot()

    def sl_set_slot(self):
        self.addLang_Button.clicked.connect(self.addLang_Button_clicked)

    def addLang_Button_clicked(self):
        self.langList_scrollArea.setWidget(self.langList_scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.langList_scrollArea)

        # 삭제 버튼
        self.langList_horizontalLayout = QHBoxLayout()
        self.del_langList_button = QPushButton("-", self.langList_scrollAreaWidgetContents)
        self.del_langList_button.setMaximumWidth(30)
        self.langList_horizontalLayout.addWidget(self.del_langList_button)

        # 언어 입력
        self.lang_lineEdit = QLineEdit(self.langList_scrollAreaWidgetContents)
        self.lang_lineEdit.setMaximumWidth(100)
        self.langList_horizontalLayout.addWidget(self.lang_lineEdit)

        # 경로 입력
        self.dir_lineEdit = QLineEdit(self.langList_scrollAreaWidgetContents)
        self.langList_horizontalLayout.addWidget(self.dir_lineEdit)

        # 경로 검색 버튼
        self.langList_toolButton = QToolButton(self.langList_scrollAreaWidgetContents)
        self.langList_horizontalLayout.addWidget(self.langList_toolButton)

        self.langList_verticalLayout.addLayout(self.langList_horizontalLayout)
        
        self.langListScroll_verticalLayout.addLayout(self.langList_verticalLayout)
        self.langList_scrollArea.setWidget(self.langList_scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.langList_scrollArea)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = UI_Setup_Language()
    ui.setupUi_Language()
    ui.show()
    sys.exit(app.exec_())
